# Generated by Django 5.0.2 on 2024-03-26 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='useraccount',
            new_name='username',
        ),
    ]
