# Generated by Django 5.0.2 on 2024-03-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_updated_at_alter_post_body_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
